# Generated by Django 3.1 on 2020-09-14 10:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200910_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
