# Generated by Django 3.1 on 2020-10-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='description',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='title',
            new_name='name',
        ),
    ]
