# Generated by Django 3.1 on 2020-10-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201005_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=20),
        ),
    ]
