# Generated by Django 3.1 on 2020-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201006_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=20),
        ),
    ]
