# Generated by Django 3.1 on 2020-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=20)),
                ('card_type', models.CharField(choices=[('master', 'master'), ('visa', 'visa'), ('paypal', 'paypal')], default='visa', max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
