# Generated by Django 3.1 on 2020-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_card_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
