# Generated by Django 3.1 on 2020-10-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201007_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
